### ISSUE TITLE
Support empty values

### ISSUE THREAD

**Issue by devidw** [shockerli/etcq#1]
Hey @shockerli 

Thanks creating this client

Wondering if we could disable the validation for the empty to allow empty values, since etcd supports those as well?

![Screenshot 2023-09-22 at 2 50 56 PM](https://github.com/shockerli/etcq/assets/68775926/2b6b4a85-26fb-4c04-a292-6959ca924143)

**Comment by shockerli** [comment]
Ok, next version will support

**Comment by devidw** [comment]
Awesome

**Comment by shockerli** [comment]
New version [1.2.4](https://github.com/shockerli/etcq/releases/tag/1.2.4) has support
